### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by azrulhaifan** [Hanafi-tech/github_laravel_ptabs#2]
Tambahkan step deployment pada file "readme", mulai dari setup env, impor database, user default dst

**Comment by Hanafi-tech** [comment]
sudah pak silahkan bisa di cek terlebih dahulu

**Comment by azrulhaifan** [comment]
Tambah product tidak bisa, stok keluar memang belum ya ?

**Comment by Hanafi-tech** [comment]
tambah produk bisa pak dilocal saya

**Comment by Hanafi-tech** [comment]
kalau stok keluar emang belum bisa waktunnya ga nyampe pak

**Comment by Hanafi-tech** [comment]
maaf pak ini saya baru cek ternyata ada yang salah di ProdukController di variabel $kodebarang2 di ubah menjadi         seperti ini pak baru bisa $kodeBarang2 = preg_replace('/[^0-9]/', '', $barang[0]->kode_terbesar);

terjadi error karena tipe string saya jumlahkan jadi error seharusnya saya ubah dulu jadi number/int baru bisa di jumlahkan
